name: cv_lab_2
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.13.5
  - pip=25.1
  - pytorch=2.7.1
  - torchvision=0.22.1
  - cpuonly
  - pip:
    - opencv-contrib-python==4.12.0
    - onnx==1.20.0